name: Notify to other repos
on:
  push:
    branches:
      - main
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Get PR URL
        id: get-pr-url
        run: |
          PR_NUMBER=$(echo ${{ github.ref }} | sed 's/refs\/pull\///')
          MERGED_PR_URL=https://github.com/${{ github.repository }}/pull/${PR_NUMBER}
          echo ${MERGED_PR_URL}

