name: Notify to other repos
on:
  push:
    branches:
      - main
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Get PR URL
        uses: jwalton/gh-find-current-pr@v1
        id: get-pr-url
        with:
          state: closed
        
      - name: Notify
        run: |
          echo "PR URL: ${{ steps.get-pr-url.outputs.pr }}"

