name: Notify to other repos
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Get PR URL
        id: get-pr-url
        run: |
          if [[ "${{ github.event.name }}" == "pull_request" ]]; then
            PR_NUMBER=${{ github.event.number }}
          else
            PR_NUMBER=0
          fi
          MERGED_PR_URL=https://github.com/${{ github.repository }}
          if [[ $PR_NUMBER > 0 ]]; then
            MERGED_PR_URL=${MERGED_PR_URL}/pull/${PR_NUMBER}
          fi
          echo ${MERGED_PR_URL}

